### ISSUE TITLE
Allow for blank data objects

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#192]
Currently the `DataJoint` expects that both OS and LM data are available even if the model being fitted is only for 1 of them (e.g. no OS model is provided).  This is a bit clunky and would be good to allow DataJoint to work even if one of them isn't available.

**Comment by danielinteractive** [comment]
The idea would be here that this kind of an ADSL dataset is provided separately to the longitudinal and survival datasets. I think this would be cleaner than. Including study and arm information in longitudinal or survival, since it would be accessible to both models and avoid dependency between them.

**Comment by danielinteractive** [comment]
Yeah we could put it in the survival data set, but then I understand people are confused why they need a survival data set when they only want to fit the longitudinal model. So it would be cleaner (and also aligned with typical CDISC data set separation) when we have one patient data set, one longitudinal data set, one survival data set.

Yes we need to be consistent with the wording, and also the names of the variables we expect in the data set etc.
