### ISSUE TITLE
Create ExponentialLongModel Object Constructor function

### ISSUE THREAD

**Issue by gowerc** [Genentech/jmpost#27]
Maybe consider a better / shorter name ?

The `initialize` method should be pre-populated with a call to a helper function that defines the correct components of the stan module perhaps something like: 

```
ExponentialStanModule <- function(
    data = "path/to/exp/code/data.stan",
    model = "path/to/exp/code/model.stan",
    functions = "path/to/exp/code/functions.stan",
    priors = list(...),
    inits = list(...)
) {
    StanModule(
        data = data,
        model = model,
        functions = functions,
        priors = priors,
        inits = inits
    )
}

setMethod(
    "initalize",
    "ExponentialModel",
    definition = function(obj, ..., stan = ExponentialStanModule()) {
        callNextMethod(obj, ..., stan = stan)
    }
)
```

**Comment by gowerc** [comment]
@charksong , Have you started this ? If not please let me know and I will pick it up as I need to close this so that I can merge my code for #34

**Comment by charksong** [comment]
Not yet, just learn Longitude process from Internet, it's ok to handle this 34 to you. I read your comment and I'm going to double check #38 and make updates. Thanks Craig.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Craig Gower-Page ***@***.***>
发送时间: Wednesday, August 10, 2022 9:28:07 PM
收件人: Genentech/jmpost ***@***.***>
抄送: Marco ***@***.***>; Mention ***@***.***>
主题: Re: [Genentech/jmpost] Create ExponentialLongModel Object Constructor function (Issue #27)


@charksong<https://github.com/charksong> , Have you started this ? If not please let me know and I will pick it up as I need to close this so that I can merge my code for #34<https://github.com/Genentech/jmpost/issues/34>

―

**Comment by gowerc** [comment]
@danielinteractive , have unassigned myself. Pushed my current code to the `add_exp_model` branch.
